<?php
use PHPUnit\Framework\TestCase;
include "../modeles/Visiteur.class.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-12-09 at 21:55:23.
 */
class VisiteurTest extends TestCase
{
    /**
     * @var Visiteur
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp():void
    {
        $this->object = new Visiteur(1, "EINSTEIN", "Albert", "14/03/1879", "75000", "Paris", "18/14/2023", "einstein.albert@science.com", "0629456325", 2,4);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown():void
    {
    }

    /**
     * @covers Visiteur::getIdVis
     * @todo   Implement testGetIdVis().
     */
    public function testGetIdVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getNomVis
     * @todo   Implement testGetNomVis().
     */
    public function testGetNomVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getPrenomVis
     * @todo   Implement testGetPrenomVis().
     */
    public function testGetPrenomVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getDateNaissVis
     * @todo   Implement testGetDateNaissVis().
     */
    public function testGetDateNaissVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getCpVis
     * @todo   Implement testGetCpVis().
     */
    public function testGetCpVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getVilleVis
     * @todo   Implement testGetVilleVis().
     */
    public function testGetVilleVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getDateArv
     * @todo   Implement testGetDateArv().
     */
    public function testGetDateArv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getEmailVis
     * @todo   Implement testGetEmailVis().
     */
    public function testGetEmailVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getTelVis
     * @todo   Implement testGetTelVis().
     */
    public function testGetTelVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getNbEnfants
     * @todo   Implement testGetNbEnfants().
     */
    public function testGetNbEnfants()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::getNbAdultes
     * @todo   Implement testGetNbAdultes().
     */
    public function testGetNbAdultes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setIdVis
     * @todo   Implement testSetIdVis().
     */
    public function testSetIdVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setNomVis
     * @todo   Implement testSetNomVis().
     */
    public function testSetNomVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setPrenomVis
     * @todo   Implement testSetPrenomVis().
     */
    public function testSetPrenomVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setDateNaissVis
     * @todo   Implement testSetDateNaissVis().
     */
    public function testSetDateNaissVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setCpVis
     * @todo   Implement testSetCpVis().
     */
    public function testSetCpVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setVilleVis
     * @todo   Implement testSetVilleVis().
     */
    public function testSetVilleVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setDateArv
     * @todo   Implement testSetDateArv().
     */
    public function testSetDateArv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setEmailVis
     * @todo   Implement testSetEmailVis().
     */
    public function testSetEmailVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setTelVis
     * @todo   Implement testSetTelVis().
     */
    public function testSetTelVis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setNbEnfants
     * @todo   Implement testSetNbEnfants().
     */
    public function testSetNbEnfants()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Visiteur::setNbAdultes
     * @todo   Implement testSetNbAdultes().
     */
    public function testSetNbAdultes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
