<?php
use PHPUnit\Framework\TestCase;

include "../modeles/VisiteurDAO.class.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-12-09 at 21:49:33.
 */
class VisiteurDAOTest extends TestCase
{

    /**
     * @var VisiteurDAO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new VisiteurDAO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    /**
     * @covers VisiteurDAO::ajouterVisiteur
     * @todo   Implement testAjouterVisiteur().
     */
    public function testAjouterVisiteur()
    {
    }
}
